### ISSUE TITLE
Make multiple renderAfter options available

### ISSUE THREAD

**Issue by b12f** [Tribex/prerenderer#10]
Currently, if `renderAfterDocumentEvent` is set, `renderAfterTime` cannot be used anymore. The project I'm working on could really use a timed kill switch, where if the event doesn't fire after n seconds, just render and exit.

I'll probably pop out a PR tomorrow where I take the `renderAfterTime` out of the `else if`.

**Comment by Tribex** [comment]
I honestly think this is not good behavior, as it introduces a race condition and could produce subtle bugs (For example, what if your network on your CI server is slow for some reason? The prerender might time out and the page would be rendered incorrectly.)

If necessary, the app developer can implement such behavior themselves by adding a timeout that sends the event in their app.

**Comment by b12f** [comment]
Hmm I get your point, but I feel like the "kill-switch" functionality should be provided by the apps' environment, not the app itself. The whole point is not make sure that rendering gets finished at some point even if the client is wholly unresponsive / never sends the event.

**Comment by Tribex** [comment]
If that's the case though, shouldn't it fail with an error rather than rendering an unintentional page?

**Comment by b12f** [comment]
Maybe both options? Technically the not-prerendered but built files are usable. For me failing with an error should be fine since I split the process into two parts; I build first, and then prerender with a second command. However if they're both part of the same command and then your build succeeded but the prerendering crashes, you might just want to continue with the build but not prerendered files.

I'm not sure though, since that's a hypothetical case. I'd be okay with just having an option to have it fail with an error after x waiting time.

**Comment by Tribex** [comment]
I might add something like that then. I much prefer fail-fast to limp-through.

**Comment by Tofandel** [comment]
I actually just added this feature by chance, given that you need to declare multiple `renderAfter` options for it, it's up to the user if they want a race for the fastest event to occur and render the page

Like this it gives the option for either a `timeout` kill switch which fails with an error or a `renderAfterTime` kill switch, which will still render the page normally and exit
