### ISSUE TITLE
`injectProperty` does nothing if `inject` is unset.

### ISSUE THREAD

**Issue by pzanitti** [Tribex/prerenderer#11]
It's more of a documentation enhancement than a bug.

If `inject` is unset, `window.__PRERENDER_INJECTED` will be undefined.

What's off-putting is that if `injectProperty` is expressly defined, `window.yourInjectProperty` will still be undefined.

I now simply use `inject: true` so that `window.hasOwnProperty('__PRERENDER_INJECTED') === true`.

**Comment by Tribex** [comment]
@pzanitti To me this is the expected behavior, otherwise you'd have to define what the default value for `injectProperty` is.
