### ISSUE TITLE
Unable to pass page.goto parameters into puppeteer prerenderer 

### ISSUE THREAD

**Issue by cbravo** [Tribex/prerenderer#15]
[referencing this issue](https://github.com/chrisvfritz/prerender-spa-plugin/issues/222)
As I mentioned in the issue I referenced above I would like to create a PR that would allow the ability to pass parameters to the page.goto call here: [link](https://github.com/Tribex/prerenderer/blob/master/renderers/renderer-puppeteer/es6/renderer.js#L112)  would you be open to me creating this PR?

**Comment by Tribex** [comment]
Added in the latest release.
Thanks a ton for the PR!
