### ISSUE TITLE
renderAfterXMLHttpRequest

### ISSUE THREAD

**Issue by qkdreyer** [Tribex/prerenderer#19]
Hello,

I was thinking about a new waitForRender option, that we could call **renderAfterXMLHttpRequest**.
This would default to false, but when truthy, we could hook into XMLHttpRequest object, and using a configurable interval (defaulting to 500ms ?), we could check if there is any pending XHR.

What do you think ?

**Comment by Tribex** [comment]
I personally think this would be too complicated to implement reliably, and instead prefer using `renderAfterDocumentEvent` after an XMLHttpRequest, which gives you more control and flexibility.
