### ISSUE TITLE
npm run build process doesn't end

### ISSUE THREAD

**Issue by afontcu** [Tribex/prerenderer#2]
Hi again :)

I ran into an issue running the plugin with `npm run build` (I'm using the default [vue webpack template](https://github.com/vuejs-templates/webpack)):

```js
// package.json
"scripts": {
  "build": "node build/build.js",
}

//webpack.prod.conf.js
new PrerendererWebpackPlugin({
  staticDir: path.resolve(__dirname, '../dist'),
  routes: [ '/', '/category/some-category' ],
  renderer: new BrowserRenderer({
    renderAfterDocumentEvent: 'api-ready'
  }),
})
```

Everything works fine, builds the whole app and prerenders correctly, but the node process does not end:

<img width="746" alt="captura de pantalla 2017-09-05 a les 11 16 17" src="https://user-images.githubusercontent.com/9197791/30054226-aebd40e8-922b-11e7-83e1-6ad14236f7ab.png">

It only happens when I load the prerenderer plugin. I also tried removing the `renderAfter` attributes but did not help.

Any ideas?

I'm on a Mac using node 8.2 and npm 5.4

Thanks again for your time!! 😇

**Comment by afontcu** [comment]
Hm, if I kill Chrome (Cmd+Q or just `killall`) then the npm process ends. This is weird...

**Comment by Tribex** [comment]
@afontcu I've run into the problem a couple times with Chrome. The page doesn't get notified properly if your app redirects to a different page while prerendering.
I'd try a different renderer or try and see how your page is redirecting, if at all.

I haven't found a solution yet.

Also, my apologies, I didn't see this issue until now. :(
