### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by ethikz** [Tribex/prerenderer#20]
Trying to install `prerender-spa-plugin` returns a 404.  Even trying to install `@prerenderer/renderer-puppeteer` returns 404

```
npm ERR! code E404
npm ERR! 404 Not Found: @prerenderer/renderer-puppeteer@^0.2.0
```

**Comment by Tribex** [comment]
I cannot seem to reproduce this. Have you figured it out yet?

**Comment by ethikz** [comment]
Nope.  I've tried that plugin, even tried `@prerenderer/renderer-puppeteer` itself with no luck.

My first guess was it's a proxy issue, since I'm behind a corporate proxy but I can install other NPM modules with no problem.

I'm going to try with `yarn` and see what happens. I'll keep you posted.

**Comment by ethikz** [comment]
Even with yarn I'm getting

`error An unexpected error occurred: "https://registry.npmjs.org/@prerenderer%2frenderer-puppeteer: User not found".`
