### ISSUE TITLE
Allow to save state just before rendering

### ISSUE THREAD

**Issue by isidrok** [Tribex/prerenderer#21]
Hi, when prerendering certain applications it is sometimes important to be able to save some state on the client, for example if using React and [loadable-components](https://github.com/smooth-code/loadable-components)  in order to avoid a dom diff and a re-render of the page we must save the loader state so we can later preload all our dynamic components that were loaded when prerendering the page. Another example could be to initialize a Redux store when prerendering but have it available on the client later.

For implementing this I see two different approaches:

1. Let the user specify a `beforeRender` option that will execute the given global function just before rendering, in that global function the user is in charge of storing the data he needs in an script tag or a data attribute and to handle serialization properly.

2. Provide a global function `beforeRender` that can be configured on the client by passing a callback that returns the application state. Then this object would be serialized and stored in a new script tag or in a data-attribute (to be compliant with csp) according to an optional second parameter.

What are your thoughts? I would be glad to P.R.

**Comment by Tribex** [comment]
I prefer option 1, though in theory you can work around it's a sense using a function that only runs if prerenderer has injected a certain variable.

**Comment by isidrok** [comment]
I prefer the first one as well, don't quite understand what you said there though.

I was thinking on evaluating `window.beforeRender` just before `page.content()`   on Puppeteer.

I don't really want to execute some function manually on the client because in that case I would have to care about when the page is fully loaded and when the prerender happens.
